### ISSUE TITLE
圆角在IE8上面不支持呀

### ISSUE THREAD

**Issue by NolaJun** [gucong3000/CSS3.js#12]
能在ie8上面进行兼容吗

**Comment by gucong3000** [comment]
这里有个DEMO
http://gucong3000.github.io/CSS3.js/demos/index.html

是不是你的页面是在本地双击运行的啊？我已经改了文档，注明了必须在web站点下运行才可生效

**Comment by gucong3000** [comment]
@NolaJun你还在么？不在我就关闭issue了
